### ISSUE TITLE
issue with wdio V7 when using  setWorldConstructor

### ISSUE THREAD

**Issue by aiNajj** [webdriverio/codemod#33]
Hello,

We have an issue when migrating from wdio V6 to V7 with the setWorldConstructor from the cucumber framework package.
We use the setWorldConstructor to get our tags from the feature file and we adapted this method for our own needs.
If we downgrade "@wdio/cucumber-framework": "<7", it works

In beforeFeature function in the config file we set the world constructor to get our tags:

```
BeforFeature(...){
	...
	setWorldConstructor(CustomWorld(tags));
	...
}
```

And then in the hooks, we call the function defined in CustomWorld (to set/get a tag).

Now with the V7 and using "@cucumber/cucumber", in the hook, we cannot call this function.
-->  `TypeError: this.FunctionName is not a function`

We need some help to understand if It's an issue on your side or if we have missed something on our configuration plz?

 I thank you in advance :))

**Comment by christian-bromann** [comment]
@aiNajj is `setWorldConstructor` a Cucumber helper or a custom implementation?

**Comment by aiNajj** [comment]
Hello @christian-bromann , it's a Cucumber helper

**Comment by christian-bromann** [comment]
@aiNajj mhm 🤔  do you have a reproducible example of this?

**Comment by christian-bromann** [comment]
Closing due to inactivity.
